apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
spec:
  nodeName: 'c1-node3'
  containers:
  - name: hello-world
    image: ghcr.io/hungtran84/hello-app:1.0
    ports:
    - containerPort: 8080
    resources:
        requests:
          memory: 128M
          cpu: 100m
        limits:
          memory: 128M
          cpu: 100m